### ISSUE TITLE
Install issue after upgrade to Venus 3.00~18

### ISSUE THREAD

**Issue by gainestr** [TimD1981/RpiTemperature#1]
RpiTemperature says that it is incompatible with beta v3.00-18.  Worked fine under 3.00-17.  Guidance appreciated.

EDIT:  I ran setup from within the /data/RpiTemperature/ folder and selected  -Uninstall (u) and restores all files to stock then selected -Install and activate (i).
RpiTemperature installed without errors and all is well.  
It appears there is an error within the gui interface for installing.  Observed the same issue with guimods.  
This is a workaround until the above gui issue is resolved.

**Comment by TimD1981** [comment]
Hello,
well, I analyzed the described issue. I installed a fresh version of V3.00-19. The RpiTemperature Package uses the SetupHelper functionality from here: https://github.com/kwindrem/SetupHelper
It look like, that the Setup Helper ist not working correctly on that version. If I select the RpiTemperature package from the list of inactive packages....SetupHelper shows the Package as "active" but there is no button to download the RpiTemperature package. So, currently I can't bring the package via Setuphelper to the venus os device. I will still investigate this issue.

**Comment by gainestr** [comment]
Yes, it looks like it was an issue with SetupHelper and has been fixed with v4.35.  I experienced the same issue as you but was able to download using SetupHelpers option to Auto Download.

**Comment by TimD1981** [comment]
I will close this issue. New SetupHelper Version V4.35 is released.
