### ISSUE TITLE
RpiTemperature crashes temperature relay monitor

### ISSUE THREAD

**Issue by kwindrem** [TimD1981/RpiTemperature#2]
With your package installed, the Settings / Relay /Temperature rules menu is blank.

I have traced the issue to dbus-tempsensor-relay service crashing. The error is:
  Error: ValueError: Invalid object path '/Settings/TempSensorRelay/Rpi-cpu06/Enabled': contains invalid character '-'

It seems you need to rename your dbus service to eliminate the invalid '-'

**Comment by Gexle** [comment]
Hello TimD1981

Please take a look at the problem Kevin reported!
Have your script using RPITemperature.

Thanks very much

**Comment by TimD1981** [comment]
Thanks for reporting the issue. I will work on it on weekend.

**Comment by Gexle** [comment]
Hello Tim

I will wait until you have the update.

Thank you

**Comment by TimD1981** [comment]
Hi, I released V1.2 (now referenced by latest). The D-Bus Service is renamed to RpiCpu and eliminate the invalid character "underline"

**Comment by TimD1981** [comment]
Released V1.2

**Comment by kwindrem** [comment]
Thanks Tim for the quick update. I can confirm the temprelay service crash is fixed and the Temperature rules menu is no longer blank.
